//
// Copyright © 2024 Alexander Romanov
// AppStoreLanguage.swift, created on 23.07.2024
//

import Foundation

public enum AppStoreLanguage: String, CaseIterable, Codable, Sendable, Identifiable {
    public var id: String {
        rawValue
    }

    case arabic = "ar-SA"
    case bengali = "bn-BD"
    case catalan = "ca"
    case chineseSimplified = "zh-Hans"
    case chineseTraditional = "zh-Hant"
    case croatian = "hr"
    case czech = "cs"
    case danish = "da"
    case dutch = "nl-NL"
    case englishUS = "en-US"
    case englishAUS = "en-AU"
    case englishCAN = "en-CA"
    case englishUK = "en-GB"
    case finnish = "fi"
    case french = "fr-FR"
    case frenchCAN = "fr-CA"
    case german = "de-DE"
    case greek = "el"
    case gujarati = "gu-IN"
    case hebrew = "he"
    case hindi = "hi"
    case hungarian = "hu"
    case indonesian = "id"
    case italian = "it"
    case japanese = "ja"
    case kannada = "kn-IN"
    case korean = "ko"
    case malay = "ms"
    case malayalam = "ml-IN"
    case marathi = "mr-IN"
    case norwegian = "no"
    case odia = "or-IN"
    case polish = "pl"
    case punjabi = "pa-IN"
    case portuguese = "pt-PT"
    case portugueseBRA = "pt-BR"
    case romanian = "ro"
    case russian = "ru"
    case slovak = "sk"
    case slovenian = "sl-SI"
    case spanish = "es-ES"
    case spanishMEX = "es-MX"
    case swedish = "sv"
    case tamil = "ta-IN"
    case telugu = "te-IN"
    case thai = "th"
    case turkish = "tr"
    case ukrainian = "uk"
    case urdu = "ur-PK"
    case vietnamese = "vi"

    public var displayName: String {
        switch self {
        case .arabic: "Arabic"
        case .bengali: "Bengali"
        case .catalan: "Catalan"
        case .chineseSimplified: "Chinese (Simplified)"
        case .chineseTraditional: "Chinese (Traditional)"
        case .croatian: "Croatian"
        case .czech: "Czech"
        case .danish: "Danish"
        case .dutch: "Dutch"
        case .englishUS: "English (US)"
        case .englishAUS: "English (Australia)"
        case .englishCAN: "English (Canada)"
        case .englishUK: "English (UK)"
        case .finnish: "Finnish"
        case .french: "French"
        case .frenchCAN: "French (Canada)"
        case .german: "German"
        case .greek: "Greek"
        case .gujarati: "Gujarati"
        case .hebrew: "Hebrew"
        case .hindi: "Hindi"
        case .hungarian: "Hungarian"
        case .indonesian: "Indonesian"
        case .italian: "Italian"
        case .japanese: "Japanese"
        case .kannada: "Kannada"
        case .korean: "Korean"
        case .malay: "Malay"
        case .malayalam: "Malayalam"
        case .marathi: "Marathi"
        case .norwegian: "Norwegian"
        case .odia: "Odia"
        case .polish: "Polish"
        case .punjabi: "Punjabi"
        case .portuguese: "Portuguese (Portugal)"
        case .portugueseBRA: "Portuguese (Brazil)"
        case .romanian: "Romanian"
        case .russian: "Russian"
        case .slovak: "Slovak"
        case .slovenian: "Slovenian"
        case .spanish: "Spanish (Spain)"
        case .spanishMEX: "Spanish (Mexico)"
        case .swedish: "Swedish"
        case .tamil: "Tamil"
        case .telugu: "Telugu"
        case .thai: "Thai"
        case .turkish: "Turkish"
        case .ukrainian: "Ukrainian"
        case .urdu: "Urdu"
        case .vietnamese: "Vietnamese"
        }
    }

    public var flagEmoji: String {
        switch self {
        case .arabic: "🇸🇦"
        case .bengali: "🇧🇩"
        case .catalan: "🇪🇸"
        case .chineseSimplified, .chineseTraditional: "🇨🇳"
        case .croatian: "🇭🇷"
        case .czech: "🇨🇿"
        case .danish: "🇩🇰"
        case .dutch: "🇳🇱"
        case .englishUS: "🇺🇸"
        case .englishAUS: "🇦🇺"
        case .englishCAN: "🇨🇦"
        case .englishUK: "🇬🇧"
        case .finnish: "🇫🇮"
        case .french: "🇫🇷"
        case .frenchCAN: "🇨🇦"
        case .german: "🇩🇪"
        case .greek: "🇬🇷"
        case .gujarati: "🇮🇳"
        case .hebrew: "🇮🇱"
        case .hindi: "🇮🇳"
        case .hungarian: "🇭🇺"
        case .indonesian: "🇮🇩"
        case .italian: "🇮🇹"
        case .japanese: "🇯🇵"
        case .kannada: "🇮🇳"
        case .korean: "🇰🇷"
        case .malay: "🇲🇾"
        case .malayalam: "🇮🇳"
        case .marathi: "🇮🇳"
        case .norwegian: "🇳🇴"
        case .odia: "🇮🇳"
        case .polish: "🇵🇱"
        case .punjabi: "🇮🇳"
        case .portuguese: "🇵🇹"
        case .portugueseBRA: "🇧🇷"
        case .romanian: "🇷🇴"
        case .russian: "🇷🇺"
        case .slovak: "🇸🇰"
        case .slovenian: "🇸🇮"
        case .spanish: "🇪🇸"
        case .spanishMEX: "🇲🇽"
        case .swedish: "🇸🇪"
        case .tamil: "🇮🇳"
        case .telugu: "🇮🇳"
        case .thai: "🇹🇭"
        case .turkish: "🇹🇷"
        case .ukrainian: "🇺🇦"
        case .urdu: "🇵🇰"
        case .vietnamese: "🇻🇳"
        }
    }
}
