//
// Copyright © 2024 Alexander Romanov
// AppStoreLanguage.swift, created on 23.07.2024
//

import Foundation

public enum AppStoreLanguage: String, CaseIterable, Codable, Sendable {
    case arabic = "ar-SA"
    case catalan = "ca"
    case chineseSimplified = "zh-Hans"
    case chineseTraditional = "zh-Hant"
    case croatian = "hr"
    case czech = "cs"
    case danish = "da"
    case dutch = "nl-NL"
    case englishUS = "en-US"
    case englishAUS = "en-AU"
    case englishCAN = "en-CA"
    case englishUK = "en-GB"
    case finnish = "fi"
    case french = "fr-FR"
    case frenchCAN = "fr-CA"
    case german = "de-DE"
    case greek = "el"
    case hebrew = "he"
    case hindi = "hi"
    case hungarian = "hu"
    case indonesian = "id"
    case italian = "it"
    case japanese = "ja"
    case korean = "ko"
    case malay = "ms"
    case macedonian = "mk"
    case norwegian = "no"
    case polish = "pl"
    case portuguese = "pt-PT"
    case portugueseBRA = "pt-BR"
    case romanian = "ro"
    case russian = "ru"
    case slovak = "sk"
    case spanish = "es-ES"
    case spanishMEX = "es-MX"
    case swedish = "sv"
    case thai = "th"
    case turkish = "tr"
    case ukrainian = "uk"
    case vietnamese = "vi"

    public var displayName: String {
        switch self {
        case .arabic: return "Arabic"
        case .catalan: return "Catalan"
        case .chineseSimplified: return "Chinese (Simplified)"
        case .chineseTraditional: return "Chinese (Traditional)"
        case .croatian: return "Croatian"
        case .czech: return "Czech"
        case .danish: return "Danish"
        case .dutch: return "Dutch"
        case .englishUS: return "English (US)"
        case .englishAUS: return "English (Australia)"
        case .englishCAN: return "English (Canada)"
        case .englishUK: return "English (UK)"
        case .finnish: return "Finnish"
        case .french: return "French"
        case .frenchCAN: return "French (Canada)"
        case .german: return "German"
        case .greek: return "Greek"
        case .hebrew: return "Hebrew"
        case .hindi: return "Hindi"
        case .hungarian: return "Hungarian"
        case .indonesian: return "Indonesian"
        case .italian: return "Italian"
        case .japanese: return "Japanese"
        case .korean: return "Korean"
        case .malay: return "Malay"
        case .macedonian: return "Macedonian"
        case .norwegian: return "Norwegian"
        case .polish: return "Polish"
        case .portuguese: return "Portuguese (Portugal)"
        case .portugueseBRA: return "Portuguese (Brazil)"
        case .romanian: return "Romanian"
        case .russian: return "Russian"
        case .slovak: return "Slovak"
        case .spanish: return "Spanish (Spain)"
        case .spanishMEX: return "Spanish (Mexico)"
        case .swedish: return "Swedish"
        case .thai: return "Thai"
        case .turkish: return "Turkish"
        case .ukrainian: return "Ukrainian"
        case .vietnamese: return "Vietnamese"
        }
    }
}
