name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - "*.*.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    name: Tests
    if:  github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
    uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
    secrets: inherit

  cache-swiftpm:
    name: Cache SwiftPM Dependencies
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache SwiftPM Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.swiftpm
            .build
          key: swiftpm-${{ runner.os }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: swiftpm-${{ runner.os }}-
  
  build-app-store-services:
    name: Build OversizeAppStoreServices
    needs: 
      - tests
      - cache-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm-all-platforms.yml@main
    with:
      package: OversizeAppStoreServices
    secrets: inherit
    
  build-metric-services:
    name: Build OversizeMetricServices
    needs: 
     - tests
     - cache-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm-all-platforms.yml@main
    with:
      package: OversizeMetricServices
    secrets: inherit

  bump:
    name: Bump version
    needs:
      - build-app-store-services
      - build-metric-services
    if: github.ref == 'refs/heads/main'
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit

  release:
    name: Create Release
    if: github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')
    uses: oversizedev/GithubWorkflows/.github/workflows/release.yml@main
    secrets: inherit
