name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - "*.*.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    name: Tests
    if:  github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
    uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
    secrets: inherit
    
  build-swiftpm:
    name: Build SwiftPM
    needs: tests
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm-all-platforms.yml@main
    with:
      package: OversizeAppStoreServices
    secrets: inherit

  bump:
    name: Bump version
    needs: build-swiftpm
    if: github.ref == 'refs/heads/main'
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit

  release:
    name: Create Release
    if: github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')
    uses: oversizedev/GithubWorkflows/.github/workflows/release.yml@main
    secrets: inherit
