name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - "*.*.*"
  workflow_dispatch:
    inputs:
      clean_cache:
        type: boolean
        description: Clean cache before building
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    name: Tests
    if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
    uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
    with:
      clean_cache: ${{ github.event.inputs.clean_cache }}
    secrets: inherit
  
  build-app-store-services:
    name: Build OversizeAppStoreServices
    needs:
      - tests
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm-all-platforms.yml@main
    with:
      package: OversizeAppStoreServices
      clean_cache: ${{ github.event.inputs.clean_cache }}
    secrets: inherit
    
  build-metric-services:
    name: Build OversizeMetricServices
    needs:
      - tests
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm-all-platforms.yml@main
    with:
      package: OversizeMetricServices
      clean_cache: ${{ github.event.inputs.clean_cache }}
    secrets: inherit

  bump:
    name: Bump version
    needs:
      - build-app-store-services
      - build-metric-services
    if: github.ref == 'refs/heads/main'
    uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
    secrets: inherit

  release:
    name: Create Release
    if: github.ref != 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')
    uses: oversizedev/GithubWorkflows/.github/workflows/release.yml@main
    secrets: inherit
