name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.9'

    - name: Set environment variable
      run: echo "PRODUCTION=true" >> $GITHUB_ENV

    - name: Build the project
      run: swift build

    - name: Run tests
      run: swift test
    
  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    with:
      package: "OversizeAppStoreServices"
    secrets: inherit
    
  tests:
     name: Test
     needs: build-swiftpm
     uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
     secrets: inherit

  bump:
     name: Bump version
     needs: tests
     if: github.ref == 'refs/heads/main'
     uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
     secrets: inherit
