name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
  
jobs:

  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    with:
      package: "OversizeAppStoreServices"
    secrets: inherit

  bump:
     name: Bump version
     needs: build-swiftpm
     if: github.ref == 'refs/heads/main'
     uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
     secrets: inherit
